services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data/"
volumes:
  db:
